import type { Allergen } from './types';

export type IngredientPreference = {
  id: string;
  labelIt: string;
  labelPl?: string;
  labelEn?: string;
  aliases: string[];
  tags: string[];
  flavourFamilies: string[];
  allergens: Allergen[];
  imageAssetId?: string;
  availabilityTier: 'standard_supermarket' | 'tesco_polish' | 'polish_shop';
  culturalWeight: number; // 1-5: how central to Polish taste/cuisine
  dietUsefulness: number; // 1-5: useful for diet-aware recipes
};

export const ingredientPreferencePool: IngredientPreference[] = [
  { id: 'potatoes', labelIt: 'Patate', labelPl: 'ziemniaki', labelEn: 'potatoes', aliases: ['kartofle'], tags: ['polish_core', 'budget', 'satiety'], flavourFamilies: ['comfort', 'starchy'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 3 },
  { id: 'cabbage', labelIt: 'Cavolo', labelPl: 'kapusta', labelEn: 'cabbage', aliases: [], tags: ['polish_core', 'budget', 'high_fibre', 'low_calorie'], flavourFamilies: ['cruciferous', 'comfort'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'sauerkraut', labelIt: 'Crauti', labelPl: 'kapusta kiszona', labelEn: 'sauerkraut', aliases: ['fermented cabbage'], tags: ['polish_core', 'fermented', 'budget', 'low_calorie'], flavourFamilies: ['sour', 'fermented'], allergens: [], imageAssetId: 'img_sauerkraut', availabilityTier: 'tesco_polish', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'pickled_cucumbers', labelIt: 'Cetrioli fermentati', labelPl: 'ogórki kiszone', labelEn: 'sour cucumbers', aliases: ['dill pickles', 'pickled cucumbers'], tags: ['polish_core', 'fermented', 'low_calorie'], flavourFamilies: ['sour', 'fermented', 'dill'], allergens: [], imageAssetId: 'img_ogorki_kiszone', availabilityTier: 'tesco_polish', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'beetroot', labelIt: 'Barbabietola', labelPl: 'buraki', labelEn: 'beetroot', aliases: ['beets'], tags: ['polish_core', 'budget', 'high_fibre'], flavourFamilies: ['earthy', 'sweet_sour'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 4 },
  { id: 'dill', labelIt: 'Aneto', labelPl: 'koperek', labelEn: 'dill', aliases: [], tags: ['polish_core', 'herb', 'low_calorie'], flavourFamilies: ['dill', 'fresh'], allergens: [], imageAssetId: 'img_dill', availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 4 },
  { id: 'mushrooms', labelIt: 'Funghi', labelPl: 'grzyby', labelEn: 'mushrooms', aliases: ['champignons'], tags: ['polish_core', 'low_calorie', 'umami'], flavourFamilies: ['mushroom', 'umami'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 4 },
  { id: 'rye_flour', labelIt: 'Farina di segale', labelPl: 'mąka żytnia', labelEn: 'rye flour', aliases: ['żur starter'], tags: ['polish_core', 'fermented'], flavourFamilies: ['sour', 'grain'], allergens: ['gluten_rye'], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 2 },
  { id: 'buckwheat', labelIt: 'Grano saraceno / kasza', labelPl: 'kasza gryczana', labelEn: 'buckwheat groats', aliases: ['kasha'], tags: ['polish_core', 'high_fibre', 'budget', 'satiety'], flavourFamilies: ['nutty', 'grain'], allergens: [], imageAssetId: 'img_kasza_gryczana', availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'pearl_barley', labelIt: 'Orzo perlato', labelPl: 'kasza jęczmienna / pęczak', labelEn: 'pearl barley', aliases: ['barley groats'], tags: ['polish_core', 'budget', 'high_fibre', 'satiety'], flavourFamilies: ['grain', 'soup'], allergens: ['gluten_barley'], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 4 },
  { id: 'twarog', labelIt: 'Twaróg / cottage cheese', labelPl: 'twaróg', labelEn: 'quark/cottage cheese', aliases: ['quark', 'cottage cheese'], tags: ['polish_core', 'protein', 'vegetarian'], flavourFamilies: ['dairy', 'sour', 'fresh'], allergens: ['milk'], imageAssetId: 'img_twarog', availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'kefir', labelIt: 'Kefir', labelPl: 'kefir', labelEn: 'kefir', aliases: [], tags: ['polish_core', 'fermented', 'protein', 'vegetarian'], flavourFamilies: ['dairy', 'sour', 'fermented'], allergens: ['milk'], imageAssetId: 'img_kefir', availabilityTier: 'tesco_polish', culturalWeight: 5, dietUsefulness: 5 },
  { id: 'greek_yogurt', labelIt: 'Yogurt greco', labelPl: 'jogurt grecki', labelEn: 'Greek yogurt', aliases: ['strained yogurt'], tags: ['protein', 'vegetarian', 'standard_swap'], flavourFamilies: ['dairy', 'sour'], allergens: ['milk'], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 5 },
  { id: 'sour_cream', labelIt: 'Panna acida / śmietana', labelPl: 'śmietana', labelEn: 'sour cream', aliases: ['smietana'], tags: ['polish_core', 'comfort'], flavourFamilies: ['dairy', 'sour'], allergens: ['milk'], availabilityTier: 'tesco_polish', culturalWeight: 5, dietUsefulness: 2 },
  { id: 'eggs', labelIt: 'Uova', labelPl: 'jaja', labelEn: 'eggs', aliases: [], tags: ['protein', 'budget', 'vegetarian'], flavourFamilies: ['rich', 'breakfast'], allergens: ['eggs'], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 5 },
  { id: 'onions', labelIt: 'Cipolle', labelPl: 'cebula', labelEn: 'onions', aliases: [], tags: ['polish_core', 'budget'], flavourFamilies: ['aromatic', 'sweet'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 5, dietUsefulness: 4 },
  { id: 'carrots', labelIt: 'Carote', labelPl: 'marchew', labelEn: 'carrots', aliases: [], tags: ['polish_core', 'budget'], flavourFamilies: ['root_veg', 'sweet'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 4 },
  { id: 'leek', labelIt: 'Porro', labelPl: 'por', labelEn: 'leek', aliases: [], tags: ['soup', 'aromatic'], flavourFamilies: ['aromatic', 'broth'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 3 },
  { id: 'celeriac', labelIt: 'Sedano rapa / sedano', labelPl: 'seler', labelEn: 'celeriac/celery', aliases: ['celery'], tags: ['soup', 'root_veg'], flavourFamilies: ['broth', 'root_veg'], allergens: ['celery'], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 3 },
  { id: 'chicken', labelIt: 'Pollo', labelPl: 'kurczak', labelEn: 'chicken', aliases: [], tags: ['protein', 'lean', 'standard_swap'], flavourFamilies: ['mild_meat'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 5 },
  { id: 'turkey_mince', labelIt: 'Tacchino macinato', labelPl: 'mielony indyk', labelEn: 'turkey mince', aliases: [], tags: ['protein', 'lean'], flavourFamilies: ['mild_meat'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 2, dietUsefulness: 5 },
  { id: 'lean_pork', labelIt: 'Maiale magro', labelPl: 'chuda wieprzowina', labelEn: 'lean pork', aliases: ['pork chop'], tags: ['protein', 'traditional'], flavourFamilies: ['pork', 'comfort'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 3 },
  { id: 'beef_mince', labelIt: 'Manzo macinato', labelPl: 'mielona wołowina', labelEn: 'beef mince', aliases: [], tags: ['protein'], flavourFamilies: ['meat', 'comfort'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 3 },
  { id: 'kielbasa', labelIt: 'Kiełbasa / salsiccia polacca', labelPl: 'kiełbasa', labelEn: 'Polish sausage', aliases: ['smoked sausage'], tags: ['polish_core', 'comfort', 'processed_meat'], flavourFamilies: ['smoky', 'meat'], allergens: [], availabilityTier: 'tesco_polish', culturalWeight: 5, dietUsefulness: 1 },
  { id: 'smoked_fish', labelIt: 'Pesce affumicato', labelPl: 'wędzona ryba', labelEn: 'smoked fish', aliases: ['herring', 'mackerel'], tags: ['protein'], flavourFamilies: ['smoky', 'fish'], allergens: ['fish'], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 4 },
  { id: 'beans', labelIt: 'Fagioli', labelPl: 'fasola', labelEn: 'beans', aliases: [], tags: ['protein', 'fibre', 'budget', 'vegetarian'], flavourFamilies: ['legume', 'stew'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 5 },
  { id: 'lentils', labelIt: 'Lenticchie', labelPl: 'soczewica', labelEn: 'lentils', aliases: [], tags: ['protein', 'fibre', 'budget', 'vegetarian'], flavourFamilies: ['legume', 'stew'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 2, dietUsefulness: 5 },
  { id: 'oats', labelIt: 'Avena', labelPl: 'owies / płatki owsiane', labelEn: 'oats', aliases: ['porridge oats'], tags: ['breakfast', 'fibre', 'budget'], flavourFamilies: ['grain'], allergens: ['gluten_oats'], availabilityTier: 'standard_supermarket', culturalWeight: 2, dietUsefulness: 5 },
  { id: 'apples', labelIt: 'Mele', labelPl: 'jabłka', labelEn: 'apples', aliases: [], tags: ['polish_core', 'budget', 'snack'], flavourFamilies: ['sweet', 'fruit'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 4 },
  { id: 'berries', labelIt: 'Frutti di bosco', labelPl: 'owoce jagodowe', labelEn: 'berries', aliases: ['blueberries', 'raspberries'], tags: ['breakfast', 'fibre'], flavourFamilies: ['fruit', 'sweet_sour'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 5 },
  { id: 'tomato_passata', labelIt: 'Passata di pomodoro', labelPl: 'passata pomidorowa', labelEn: 'tomato passata', aliases: ['tomato sauce'], tags: ['soup', 'budget'], flavourFamilies: ['tomato', 'sweet_sour'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 4 },
  { id: 'cucumber', labelIt: 'Cetriolo fresco', labelPl: 'ogórek', labelEn: 'cucumber', aliases: [], tags: ['low_calorie', 'fresh'], flavourFamilies: ['fresh', 'dill'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 5 },
  { id: 'radish', labelIt: 'Ravanelli', labelPl: 'rzodkiewka', labelEn: 'radish', aliases: [], tags: ['fresh', 'low_calorie'], flavourFamilies: ['peppery', 'fresh'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 4 },
  { id: 'chives', labelIt: 'Erba cipollina', labelPl: 'szczypiorek', labelEn: 'chives', aliases: ['spring onion'], tags: ['herb', 'fresh'], flavourFamilies: ['onion', 'fresh'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 4 },
  { id: 'horseradish', labelIt: 'Rafano', labelPl: 'chrzan', labelEn: 'horseradish', aliases: [], tags: ['polish_core', 'condiment'], flavourFamilies: ['sharp', 'sour'], allergens: [], availabilityTier: 'tesco_polish', culturalWeight: 4, dietUsefulness: 3 },
  { id: 'mustard', labelIt: 'Senape', labelPl: 'musztarda', labelEn: 'mustard', aliases: [], tags: ['condiment'], flavourFamilies: ['sharp'], allergens: ['mustard'], availabilityTier: 'standard_supermarket', culturalWeight: 3, dietUsefulness: 2 },
  { id: 'garlic', labelIt: 'Aglio', labelPl: 'czosnek', labelEn: 'garlic', aliases: [], tags: ['aromatic'], flavourFamilies: ['aromatic'], allergens: [], availabilityTier: 'standard_supermarket', culturalWeight: 4, dietUsefulness: 3 }
];
